"""Real yt-dlp + FFmpeg integration against media generated by this test suite.

No third-party media or YouTube downloads. The local HTTP server is a test fixture,
not a production downloader.
"""
import functools
import http.server
import json
import threading
import time
from pathlib import Path
import pytest
from app.models.download import Options, State
from app.services.process import run_hidden
from app.services.ffmpeg import FFmpegService
from app.utils.paths import runtime_dir


@pytest.fixture(scope="module")
def local_media(tmp_path_factory):
    folder = tmp_path_factory.mktemp("original-media")
    ffmpeg = runtime_dir() / "ffmpeg" / "ffmpeg.exe"
    if not ffmpeg.exists():
        pytest.skip("Run scripts/bootstrap_runtime.py to install the integration runtime")
    result = run_hidden([ffmpeg, "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "testsrc2=size=320x180:rate=24",
        "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=44100", "-t", "2", "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "128k", "-metadata", "title=MediaGrab original test", folder / "original.mp4"], timeout=30)
    assert result.returncode == 0, result.stderr
    repeated = run_hidden([ffmpeg, "-hide_banner", "-loglevel", "error", "-stream_loop", "4", "-i", folder / "original.mp4", "-c", "copy", "-movflags", "+faststart", folder / "slow.mp4"], timeout=30)
    assert repeated.returncode == 0
    cover = run_hidden([ffmpeg, "-hide_banner", "-loglevel", "error", "-i", folder / "original.mp4", "-frames:v", "1", folder / "cover.jpg"], timeout=30)
    assert cover.returncode == 0
    (folder / "captions.vtt").write_text("WEBVTT\n\n00:00.000 --> 00:01.500\nOriginal test caption\n", "utf-8")
    (folder / "film.html").write_text('<html><head><title>Original film</title></head><body><video controls poster="cover.jpg"><source src="original.mp4" type="video/mp4"><track kind="subtitles" src="captions.vtt" srclang="en" label="English"></video></body></html>', "utf-8")
    class QuietHandler(http.server.SimpleHTTPRequestHandler):
        def log_message(self, *args):
            pass

        def do_GET(self):
            if self.path != "/slow.mp4":
                return super().do_GET()
            payload = (folder / "slow.mp4").read_bytes()
            range_header = self.headers.get("Range", "")
            start = int(range_header.split("=")[1].split("-")[0]) if range_header else 0
            if start:
                (folder / "range-used.txt").write_text(str(start))
            self.send_response(206 if start else 200)
            self.send_header("Content-Type", "video/mp4")
            self.send_header("Accept-Ranges", "bytes")
            self.send_header("Content-Length", str(len(payload) - start))
            if start:
                self.send_header("Content-Range", f"bytes {start}-{len(payload)-1}/{len(payload)}")
            self.end_headers()
            try:
                for index in range(start, len(payload), 1024):
                    self.wfile.write(payload[index:index + 1024])
                    self.wfile.flush()
                    time.sleep(.001)
            except (ConnectionError, OSError):
                pass
    handler = functools.partial(QuietHandler, directory=str(folder))
    server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    yield f"http://127.0.0.1:{server.server_port}/original.mp4", folder
    server.shutdown()
    server.server_close()
    thread.join()


def probe(path):
    result = run_hidden([runtime_dir() / "ffmpeg" / "ffprobe.exe", "-v", "error", "-show_streams", "-show_format", "-of", "json", path], timeout=20)
    assert result.returncode == 0, result.stderr
    return json.loads(result.stdout)


def test_real_info(service, qtbot, local_media):
    url, _ = local_media
    with qtbot.waitSignal(service.info_ready, timeout=45000) as signal:
        service.get_info(url)
    assert signal.args[1]["title"] == "original"
    assert signal.args[1]["formats"]
    qtbot.waitUntil(lambda: not service.inspectors)


@pytest.mark.parametrize("mode,container,codec", [
    ("Video", "MP4", "h264"), ("Video", "MKV", "h264"), ("Video", "WEBM", "vp9"),
    ("Audio", "MP3", "mp3"), ("Audio", "WAV", "pcm_s16le"), ("Audio", "M4A", "aac"),
    ("Audio", "OPUS", "opus"), ("Audio", "FLAC", "flac"), ("Audio", "Original / Best Audio", "aac"),
])
def test_real_formats(service, qtbot, local_media, mode, container, codec):
    url, _ = local_media
    job = service.add(url, {"title": "Original : test", "playlist_title": "Original collection", "playlist_index": 3}, Options(mode=mode, container=container))
    service.enqueue(job)
    qtbot.waitUntil(lambda: job.state in {State.COMPLETED, State.FAILED}, timeout=90000)
    assert job.state == State.COMPLETED, job.error
    assert Path(job.output).exists()
    assert "Original _ test" in Path(job.output).name
    data = probe(job.output)
    streams = data["streams"]
    assert any(s["codec_name"] == codec for s in streams), data
    if mode == "Audio":
        assert not any(s["codec_type"] == "video" for s in streams)
        assert data["format"].get("tags", {}).get("album") == "Original collection" or container in {"WAV", "OPUS"}
    if container == "WAV":
        assert streams[0]["sample_rate"] == "44100"
    assert not Path(job.stage).exists()


def test_real_name_conflict(service, qtbot, local_media):
    url, _ = local_media
    jobs = [service.add(url, {"title": "Same title"}) for _ in range(2)]
    for job in jobs:
        service.enqueue(job)
    qtbot.waitUntil(lambda: all(j.state in {State.COMPLETED, State.FAILED} for j in jobs), timeout=90000)
    assert all(j.state == State.COMPLETED for j in jobs)
    assert {Path(j.output).name for j in jobs} == {"Same title.mp4", "Same title (1).mp4"}


def test_ffmpeg_detection(runtime):
    service = FFmpegService(runtime.ffmpeg_dir())
    assert service.check_installation()
    assert service.get_version().startswith("ffmpeg version")


def test_real_pause_resume_and_cancel(service, qtbot, local_media, monkeypatch):
    url, folder = local_media
    slow = url.replace("original.mp4", "slow.mp4")
    base_args = service.runtime.base_args
    monkeypatch.setattr(service.runtime, "base_args", lambda: base_args() + ["--limit-rate", "32K", "--no-resize-buffer", "--buffer-size", "4K"])
    observed = []
    service.events.progress.connect(lambda key, data: observed.append(data))
    job = service.add(slow, {"title": "Resume integration"})
    service.enqueue(job)
    qtbot.waitUntil(lambda: job.progress >= 20 or job.state == State.FAILED, timeout=45000)
    assert job.state == State.DOWNLOADING, observed
    service.pause(job)
    qtbot.waitUntil(lambda: job.state == State.PAUSED, timeout=20000)
    assert list(Path(job.stage).glob("*.part"))
    service.retry(job)
    qtbot.waitUntil(lambda: job.state in {State.COMPLETED, State.FAILED}, timeout=45000)
    assert job.state == State.COMPLETED, job.error
    assert (folder / "range-used.txt").exists(), "Resume should issue an HTTP Range request"
    assert probe(job.output)["streams"]
    cancelled = service.add(slow, {"title": "Cancel integration"})
    service.enqueue(cancelled)
    qtbot.waitUntil(lambda: cancelled.progress >= 10 or cancelled.state == State.FAILED, timeout=45000)
    stage = Path(cancelled.stage)
    service.cancel(cancelled)
    qtbot.waitUntil(lambda: cancelled.state == State.CANCELLED, timeout=20000)
    assert not stage.exists()
    assert not cancelled.output


@pytest.mark.parametrize("subtitle_mode", ["Embed into video", "Download .srt separately"])
def test_real_subtitles(service, qtbot, local_media, subtitle_mode):
    url, _ = local_media
    job = service.add(url.replace("original.mp4", "film.html"), {"title": "Caption test"}, Options(subtitle="en", subtitle_mode=subtitle_mode))
    service.enqueue(job)
    qtbot.waitUntil(lambda: job.state in {State.COMPLETED, State.FAILED}, timeout=45000)
    assert job.state == State.COMPLETED, job.error
    if subtitle_mode == "Embed into video":
        assert any(s["codec_type"] == "subtitle" for s in probe(job.output)["streams"])
    else:
        sidecars = list(Path(job.destination).glob("*.srt"))
        assert len(sidecars) == 1
        assert "Original test caption" in sidecars[0].read_text("utf-8")


def test_real_mp3_artwork(service, qtbot, local_media):
    url, _ = local_media
    job = service.add(url.replace("original.mp4", "film.html"), {"title": "Artwork test"}, Options("Audio", "MP3", "192 kbps", thumbnail=True))
    service.enqueue(job)
    qtbot.waitUntil(lambda: job.state in {State.COMPLETED, State.FAILED}, timeout=45000)
    assert job.state == State.COMPLETED, job.error
    streams = probe(job.output)["streams"]
    assert any(s.get("disposition", {}).get("attached_pic") == 1 for s in streams)

@pytest.mark.parametrize('container,extension',[('MP3','.mp3'),('Original / Best Audio','.m4a')])
def test_catalog_tags_cover_lyrics_and_custom_name(service,qtbot,local_media,monkeypatch,container,extension):
    import app.services.download as engine
    url,folder=local_media
    monkeypatch.setattr(engine,'lyrics_for',lambda info:{'text':'[00:00.00]Original test lyric','extension':'.lrc'})
    info={'title':'First Light','artist':'INTAKE Studio','album':'Original Sessions','catalog':'Spotify','source_url':url,'match_score':1,'thumbnail':url.replace('original.mp4','cover.jpg'),'release_date':'2026-01-01','duration':2}
    job=service.add('https://open.spotify.com/track/fixture',info,Options(mode='Audio',container=container,thumbnail=True,filename='My own recording'))
    service.enqueue(job); qtbot.waitUntil(lambda:job.state in {State.COMPLETED,State.FAILED},timeout=45000)
    assert job.state==State.COMPLETED,job.error
    assert Path(job.output).name=='My own recording'+extension
    data=probe(job.output); tags=data['format']['tags']
    assert tags['title']=='First Light' and tags['artist']=='INTAKE Studio' and tags['album']=='Original Sessions'
    assert any(stream.get('disposition',{}).get('attached_pic') for stream in data['streams'])
    assert (Path(job.output).with_suffix('.lrc')).read_text('utf-8').endswith('Original test lyric')


def test_auto_video_best_streams_real(service,qtbot,local_media):
    url,_=local_media; job=service.add(url,{'title':'Automatic quality'},Options(container='Auto'))
    service.enqueue(job); qtbot.waitUntil(lambda:job.state in {State.COMPLETED,State.FAILED},timeout=45000)
    assert job.state==State.COMPLETED,job.error
    streams=probe(job.output)['streams']; assert {s['codec_type'] for s in streams}>={'video','audio'}
